### ISSUE TITLE
No IOS Support

### ISSUE THREAD

**Issue by electriko3** [antonmolchan/gdpr_dialog_flutter#1]
Thank you man, great library! When will iOS be implemented?

**Comment by maxcorrads** [comment]
Hi @electriko3, if you are still interested here https://github.com/maxcorrads/gdpr_dialog_flutter/commit/e64a06e61c28546eb464795e6df2e557759c5976 I have implemented a very rude and primitive iOS support. 
As soon as I have time I I will improve it and send a PR.

**Comment by antonmolchan** [comment]
Hi, the new version of the library supports iOS functionality
