### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method gdpr.activate on channel gdpr_dialog))

### ISSUE THREAD

**Issue by brahim-dev** [antonmolchan/gdpr_dialog_flutter#2]
MissingPluginException (MissingPluginException(No implementation found for method gdpr.activate on channel gdpr_dialog))
when i run the application this error shown  
![Annotation 2020-03-05 100834](https://user-images.githubusercontent.com/59501110/75965611-56727300-5ec9-11ea-8dc3-e74146e0da16.png)

**Comment by antonmolchan** [comment]
Hi, sorry for the long answer. Maybe you need to import the GDPR library at the top of the dart file?
