### ISSUE TITLE
iOS pod install error to add this package.

### ISSUE THREAD

**Issue by Vishal949** [antonmolchan/gdpr_dialog_flutter#22]
**[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/-/StudioProjects/Tonk/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework/GoogleMobileAds.xcframework)**

`call **pod install** command in terminal to give above error for iOS.`

**Comment by awaitANTHONY** [comment]
Hello you can fixed this issue just replace one line in Ios/Podfile ![IMG-20230709-WA0020.jpg](https://github.com/antonmolchan/gdpr_dialog_flutter/assets/81618197/bc3d75c5-ec30-4864-b0f7-71078ad0ce57)

To 
![IMG-20230709-WA0019.jpg](https://github.com/antonmolchan/gdpr_dialog_flutter/assets/81618197/7d97b32d-dcbc-4e5f-bbd3-b0c837ec3635)

**Comment by Vishal949** [comment]
Done @awaitANTHONY ,, Thank You 👍
