### ISSUE TITLE
Consent update

### ISSUE THREAD

**Issue by zgauhar** [antonmolchan/gdpr_dialog_flutter#3]
The consent description states that the user can change their consent any time from the settings. However, when i try to call the same method from my settings page, the dialog is not shown and the consent status stays the same as previously selected. I have double checked and the method is called but no dialog.

Please let me know when this would be resolved or you could provide the option to write custom description for consent form.

**Comment by antonmolchan** [comment]
Hi, I know about that.
In a few weeks, I will try to write another function that will change user consent.

**Comment by Tobivaria** [comment]
You can just call 
    await reset();
    await showDialog();

works for me

**Comment by dartsliebe** [comment]
Hello everyone, 

is there any update on this? On Android, reopening (via button click) does not work.
On iOS there is no issue...

`
onPressed: () {

                                GdprDialog.instance
                                    .showDialog('pub-###################', 'https://www.test.com/app-privacy-policy', isForTest: false)
                                    .then((onValue) {
                                  setState(() { print( onValue); });
                                });

                              },
`

Best Regards,
Tim

**Comment by antonmolchan** [comment]
Hi, on android you can change status to unknown then open the dialog, functionality on native code on android and ios same but i think it's specific on android platform

**Comment by vmkgalvatron** [comment]
Hey does message pop up in EEA? 
If so how can I see it outside EEA for debugging?
