### ISSUE TITLE
Forward consent to the Google Mobile Ads SDK

### ISSUE THREAD

**Issue by cyberlahy** [antonmolchan/gdpr_dialog_flutter#4]
Hi,
awesome package,
After getting consent, is it automatically report to the consent sdk?
and do we need to forward consent to the google mobile ads sdk or not?
as stated in documentation:

> After reporting consent to the Consent SDK, you can forward consent to the Google Mobile Ads SDK.

and also do we need Delay app measurement ?
```
<manifest>
     <application>
        <!-- Delay app measurement until MobileAds.initialize() is called. -->
        <meta-data
            android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT"
            android:value="true"/>
    </application>
</manifest>
```

thanks

**Comment by antonmolchan** [comment]
Hi, this package uses a native dialog that sends status to Google.
And in my project I send consent status when initializing banners
I am using the https://pub.dev/packages/firebase_admob package which contains targetInInfo with a personalized status

**Comment by cyberlahy** [comment]
Hi,
thanks
