### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Tobivaria** [antonmolchan/gdpr_dialog_flutter#5]
To give credit where credit is due, there needs to be a license for this package, so other developers can integrate it.

**Comment by antonmolchan** [comment]
@Tobivaria Hi, i am update library now. Add license.

**Comment by Tobivaria** [comment]
@antonmolchan don't forget to close issues, when they are fixed. Otherwise the issue tab will get crowded.
Thanks for the update :)
