### ISSUE TITLE
Hey does message pop up in EEA only?

### ISSUE THREAD

**Issue by vmkgalvatron** [antonmolchan/gdpr_dialog_flutter#7]
Hey does message pop up in EEA only?
If so how can I see it outside EEA for debugging?

**Comment by antonmolchan** [comment]
Hi.
1) Yep, this message pop only in EEA.
2) On android you can test library using this code 
`GdprDialog.instance.showDialog('your pub id', 'link to policy, isForTest: true, testDeviceId: 'test device ID');`
It will set the debug location in Europe and you will see a popup message.
Only the first two parameters are needed to build the release.

**Comment by vmkgalvatron** [comment]
@antonmolchan 

Please check if code below is correct because I am unable to see the message.


`class _AppState extends State<App> {
  @override
  void initState() {
    super.initState();
    GdprDialog.instance
        .showDialog('pub-9742820678776617', 'https://sites.google.com/enlist',
            isForTest: true, testDeviceId: '')
        .then((onValue) {
      print('result === $onValue');
    });
    currentTheme.addListener(() {
      setState(() {});
    });
  }`

**Comment by antonmolchan** [comment]
@vmkgalvatron  you need to write your real link, google get some data from that

**Comment by vmkgalvatron** [comment]
Hi @antonmolchan,  
              Thanks for the support and providing the library for free.  

I was putting the 'Advertising ID' given in Settings of phone in 'testDevice ID' parameter. It turns out that I had to some other String which appeared in terminal in a line

`Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("E044C97978FC060327A4C4F01EE86A88")) to get test ads on this device.`

Once I put "E044C97978FC060327A4C4F01EE86A88" in testDeviceID it was perfectly working.

What is "E044C97978FC060327A4C4F01EE86A88" and how to find it because Advertising ID in my phone was '9c8f7006-888e-49a0-83fb-336b3dd02957'?

**Comment by antonmolchan** [comment]
@vmkgalvatron Hm, this is weird because I got the test id from
`Use RequestConfiguration.Builder (). SetTestDeviceIds (Arrays.asList ("test ID")) `
I wrote this code about half a year ago, maybe Google has changed something now.
For a real test, I have installed a European vpn and am testing the library in release mode =)

**Comment by vmkgalvatron** [comment]
Yes there may be some changes. 
Do I have to to store the result of dialogue or funding choices and admob will manage it?

**Comment by antonmolchan** [comment]
@vmkgalvatron 
I use `GdprDialog.instance.getConsentStatus()` and then get 3 type of answers:
`UNKNOWN,NON_PERSONALIZED and PERSONALIZED` 
And then if status `UNKNOWN` call dialog of consent another one use admob library
