### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by Tobivaria** [antonmolchan/gdpr_dialog_flutter#8]
Will this package be updated to support null safety?

**Comment by antonmolchan** [comment]
Hi, I will upgrade package in the near future

**Comment by Tobivaria** [comment]
Hi @antonmolchan,
this is my last package left for upgrading my production app :).
Do you have rough plan when null safety will arrive?

**Comment by antonmolchan** [comment]
@Tobivaria  
Hey, i arrived null safety in my package, but have some problem to publish it in pub dev.
Have exception 
A private package cannot be published.
You can enable this by changing the "publish_to" field in your pubspec.

Dont know how to fix it

**Comment by antonmolchan** [comment]
Ok, i pushed latest changes to git and pub dev site

**Comment by kaboc** [comment]
@antonmolchan 
What is the reason why you changed all methods to return `Future<dynamic>`?

**Comment by antonmolchan** [comment]
@kaboc because invokeMethod return Future<T?> construction. I looked at the solution from other packages and came to this. In the future I will find a more concise solution.

**Comment by kaboc** [comment]
@antonmolchan 
You have to specify the generic type to make `invokeMethod<T>()` return a type other than `dynamic`.

e.g. `await invokeMethod<bool>(...)` returns `bool?`.

The return type has `?`, which means nullable, so you need to decide whether to return the nullable type as is or convert it to non-null before returning it. Probably the latter is more user-friendly.

**Comment by antonmolchan** [comment]
@kaboc 
I am refactor my code and now return not dynamic value and if invokeMethod returned null value i change it to to default.
Thanks for help.
